import { sql } from "drizzle-orm";
import { pgTable, text, varchar, integer, timestamp, jsonb, boolean, index, serial, uuid } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { projects } from "./schema";
import { users } from "./schema";
import { days } from "./schema";

// ────────────────────────────────────────────────────────────────────────────
// SAFETY CHECKLISTS (Template definitions)
// ────────────────────────────────────────────────────────────────────────────

export type ChecklistType = "pre_dive" | "post_dive" | "equipment";
export type ChecklistRole = "diver" | "tender" | "supervisor" | "all";

export const safetyChecklists = pgTable("safety_checklists", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  projectId: varchar("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  checklistType: text("checklist_type").notNull().$type<ChecklistType>(),
  title: text("title").notNull(),
  description: text("description"),
  roleScope: text("role_scope").notNull().$type<ChecklistRole>().default("all"),
  isActive: boolean("is_active").default(true).notNull(),
  version: integer("version").notNull().default(1),
  createdBy: varchar("created_by").notNull().references(() => users.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectIdx: index("safety_checklists_project_idx").on(t.projectId),
  typeIdx: index("safety_checklists_type_idx").on(t.checklistType),
}));

export const insertSafetyChecklistSchema = createInsertSchema(safetyChecklists).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertSafetyChecklist = z.infer<typeof insertSafetyChecklistSchema>;
export type SafetyChecklist = typeof safetyChecklists.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// CHECKLIST ITEMS (Individual items within a checklist template)
// ────────────────────────────────────────────────────────────────────────────

export type ChecklistItemType = "checkbox" | "pass_fail_flag" | "text_input" | "numeric_input" | "gas_analysis";

export const checklistItems = pgTable("checklist_items", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  checklistId: varchar("checklist_id").notNull().references(() => safetyChecklists.id, { onDelete: "cascade" }),
  sortOrder: integer("sort_order").notNull().default(0),
  category: text("category"),
  label: text("label").notNull(),
  description: text("description"),
  itemType: text("item_type").notNull().$type<ChecklistItemType>().default("checkbox"),
  isRequired: boolean("is_required").default(true).notNull(),
  equipmentCategory: text("equipment_category"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  checklistIdx: index("checklist_items_checklist_idx").on(t.checklistId),
}));

export const insertChecklistItemSchema = createInsertSchema(checklistItems).omit({ id: true, createdAt: true });
export type InsertChecklistItem = z.infer<typeof insertChecklistItemSchema>;
export type ChecklistItem = typeof checklistItems.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// CHECKLIST COMPLETIONS (Filled-out checklists with digital signatures)
// ────────────────────────────────────────────────────────────────────────────

export type CompletionStatus = "in_progress" | "completed" | "completed_with_issues";

export interface ChecklistResponse {
  itemId: string;
  label: string;
  value: string | boolean | number;
  status?: "pass" | "fail" | "flag";
  notes?: string;
}

export const checklistCompletions = pgTable("checklist_completions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  checklistId: varchar("checklist_id").notNull().references(() => safetyChecklists.id, { onDelete: "cascade" }),
  projectId: varchar("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  dayId: varchar("day_id").references(() => days.id, { onDelete: "set null" }),
  completedBy: varchar("completed_by").notNull().references(() => users.id),
  completedByName: text("completed_by_name"),
  status: text("status").notNull().$type<CompletionStatus>().default("in_progress"),
  responses: jsonb("responses").$type<ChecklistResponse[]>().notNull().default([]),
  digitalSignature: text("digital_signature"),
  signedAt: timestamp("signed_at", { withTimezone: true }),
  notes: text("notes"),
  autoGeneratedRiskIds: jsonb("auto_generated_risk_ids").$type<string[]>().default([]),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectIdx: index("checklist_completions_project_idx").on(t.projectId),
  dayIdx: index("checklist_completions_day_idx").on(t.dayId),
  completedByIdx: index("checklist_completions_user_idx").on(t.completedBy),
}));

export const insertChecklistCompletionSchema = createInsertSchema(checklistCompletions).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertChecklistCompletion = z.infer<typeof insertChecklistCompletionSchema>;
export type ChecklistCompletion = typeof checklistCompletions.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// JHA RECORDS (Job Hazard Analysis — AI-generated, supervisor-approved)
// ────────────────────────────────────────────────────────────────────────────

export type JhaStatus = "draft" | "pending_review" | "approved" | "superseded";

export interface JhaHazardEntry {
  hazard: string;
  riskLevel: "low" | "medium" | "high" | "critical";
  controls: string[];
  responsibleParty: string;
  ppe?: string[];
}

export interface JhaContent {
  jobDescription: string;
  location: string;
  date: string;
  weatherConditions?: string;
  diveDepth?: number;
  equipmentInUse?: string[];
  plannedOperations?: string[];
  hazards: JhaHazardEntry[];
  emergencyProcedures?: string[];
  additionalNotes?: string;
  historicalIncidentsSummary?: string;
  aiModel?: string;
  aiPromptVersion?: string;
}

export const jhaRecords = pgTable("jha_records", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  projectId: varchar("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  dayId: varchar("day_id").references(() => days.id, { onDelete: "set null" }),
  title: text("title").notNull(),
  status: text("status").notNull().$type<JhaStatus>().default("draft"),
  content: jsonb("content").$type<JhaContent>().notNull(),
  aiGenerated: boolean("ai_generated").default(false).notNull(),
  generatedBy: varchar("generated_by").notNull().references(() => users.id),
  reviewedBy: varchar("reviewed_by").references(() => users.id),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  approvedBy: varchar("approved_by").references(() => users.id),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  digitalSignature: text("digital_signature"),
  exportFileId: varchar("export_file_id"),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectIdx: index("jha_records_project_idx").on(t.projectId),
  dayIdx: index("jha_records_day_idx").on(t.dayId),
  statusIdx: index("jha_records_status_idx").on(t.status),
}));

export const insertJhaRecordSchema = createInsertSchema(jhaRecords).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertJhaRecord = z.infer<typeof insertJhaRecordSchema>;
export type JhaRecord = typeof jhaRecords.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// SAFETY MEETINGS (Morning safety meeting records)
// ────────────────────────────────────────────────────────────────────────────

export type SafetyMeetingStatus = "draft" | "in_progress" | "completed";

export interface SafetyMeetingAgenda {
  safetyTopicOfDay: string;
  previousShiftSummary: {
    workCompleted: string[];
    issues: string[];
    nearMisses: string[];
  };
  todaysHazards: {
    hazard: string;
    mitigation: string;
  }[];
  openDiscussionPoints: string[];
  supervisorQuestions: {
    question: string;
    answer?: string;
  }[];
  weatherConditions?: string;
  equipmentStatusFlags?: string[];
  plannedOperations?: string[];
}

export const safetyMeetings = pgTable("safety_meetings", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  projectId: varchar("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  dayId: varchar("day_id").references(() => days.id, { onDelete: "set null" }),
  title: text("title").notNull(),
  meetingDate: text("meeting_date").notNull(),
  status: text("status").notNull().$type<SafetyMeetingStatus>().default("draft"),
  agenda: jsonb("agenda").$type<SafetyMeetingAgenda>().notNull(),
  aiGenerated: boolean("ai_generated").default(false).notNull(),
  conductedBy: varchar("conducted_by").notNull().references(() => users.id),
  conductedByName: text("conducted_by_name"),
  attendees: jsonb("attendees").$type<string[]>().default([]),
  duration: integer("duration_minutes"),
  notes: text("notes"),
  digitalSignature: text("digital_signature"),
  signedAt: timestamp("signed_at", { withTimezone: true }),
  exportFileId: varchar("export_file_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectIdx: index("safety_meetings_project_idx").on(t.projectId),
  dayIdx: index("safety_meetings_day_idx").on(t.dayId),
  dateIdx: index("safety_meetings_date_idx").on(t.meetingDate),
}));

export const insertSafetyMeetingSchema = createInsertSchema(safetyMeetings).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertSafetyMeeting = z.infer<typeof insertSafetyMeetingSchema>;
export type SafetyMeeting = typeof safetyMeetings.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// NEAR-MISS REPORTS (Frictionless incident/near-miss capture)
// ────────────────────────────────────────────────────────────────────────────

export type NearMissSeverity = "low" | "medium" | "high" | "critical";
export type NearMissStatus = "reported" | "under_review" | "resolved" | "closed";

export const nearMissReports = pgTable("near_miss_reports", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  projectId: varchar("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  dayId: varchar("day_id").references(() => days.id, { onDelete: "set null" }),
  reportedBy: varchar("reported_by").notNull().references(() => users.id),
  reportedByName: text("reported_by_name"),
  title: text("title").notNull(),
  description: text("description").notNull(),
  location: text("location"),
  severity: text("severity").notNull().$type<NearMissSeverity>().default("low"),
  status: text("status").notNull().$type<NearMissStatus>().default("reported"),
  category: text("category"),
  involvedPersonnel: jsonb("involved_personnel").$type<string[]>().default([]),
  immediateActions: text("immediate_actions"),
  rootCause: text("root_cause"),
  correctiveActions: text("corrective_actions"),
  linkedRiskId: varchar("linked_risk_id"),
  voiceTranscript: text("voice_transcript"),
  reviewedBy: varchar("reviewed_by").references(() => users.id),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  resolvedBy: varchar("resolved_by").references(() => users.id),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  projectIdx: index("near_miss_reports_project_idx").on(t.projectId),
  dayIdx: index("near_miss_reports_day_idx").on(t.dayId),
  severityIdx: index("near_miss_reports_severity_idx").on(t.severity),
  statusIdx: index("near_miss_reports_status_idx").on(t.status),
}));

export const insertNearMissReportSchema = createInsertSchema(nearMissReports).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertNearMissReport = z.infer<typeof insertNearMissReportSchema>;
export type NearMissReport = typeof nearMissReports.$inferSelect;


// ────────────────────────────────────────────────────────────────────────────
// SAFETY TOPIC LIBRARY (Pre-loaded safety meeting topics)
// ────────────────────────────────────────────────────────────────────────────

export type SafetyTopicCategory =
  | "entanglement"
  | "loss_of_gas"
  | "communications_failure"
  | "hypothermia"
  | "barotrauma"
  | "equipment_failure"
  | "weather_current"
  | "crane_operations"
  | "cutting_welding"
  | "confined_space"
  | "contaminated_water"
  | "general";

export const safetyTopicLibrary = pgTable("safety_topic_library", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  category: text("category").notNull().$type<SafetyTopicCategory>(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  talkingPoints: jsonb("talking_points").$type<string[]>().notNull().default([]),
  applicableDiveTypes: jsonb("applicable_dive_types").$type<string[]>().default([]),
  regulatoryReferences: jsonb("regulatory_references").$type<string[]>().default([]),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  categoryIdx: index("safety_topic_library_category_idx").on(t.category),
}));

export const insertSafetyTopicSchema = createInsertSchema(safetyTopicLibrary).omit({ id: true, createdAt: true });
export type InsertSafetyTopic = z.infer<typeof insertSafetyTopicSchema>;
export type SafetyTopic = typeof safetyTopicLibrary.$inferSelect;

// ────────────────────────────────────────────────────────────────────────────
// JHA HAZARD LIBRARY (Common commercial diving hazards for JHA generation)
// ────────────────────────────────────────────────────────────────────────────

export type JhaHazardCategory =
  | "environmental"
  | "equipment"
  | "physiological"
  | "operational"
  | "chemical"
  | "mechanical"
  | "electrical";

export const jhaHazardLibrary = pgTable("jha_hazard_library", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  category: text("category").notNull().$type<JhaHazardCategory>(),
  hazard: text("hazard").notNull(),
  description: text("description").notNull(),
  defaultRiskLevel: text("default_risk_level").notNull().$type<"low" | "medium" | "high" | "critical">().default("medium"),
  standardControls: jsonb("standard_controls").$type<string[]>().notNull().default([]),
  requiredPpe: jsonb("required_ppe").$type<string[]>().default([]),
  applicableOperations: jsonb("applicable_operations").$type<string[]>().default([]),
  regulatoryBasis: text("regulatory_basis"),
  isActive: boolean("is_active").default(true).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => ({
  categoryIdx: index("jha_hazard_library_category_idx").on(t.category),
}));

export const insertJhaHazardSchema = createInsertSchema(jhaHazardLibrary).omit({ id: true, createdAt: true });
export type InsertJhaHazard = z.infer<typeof insertJhaHazardSchema>;
export type JhaHazard = typeof jhaHazardLibrary.$inferSelect;
